package com.itzhouq.mybatisgenerator.dao;

import com.itzhouq.mybatisgenerator.domain.SysLog;
import java.util.List;

public interface SysLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_log
     *
     * @mbg.generated
     */
    int insert(SysLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_log
     *
     * @mbg.generated
     */
    SysLog selectByPrimaryKey(String logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_log
     *
     * @mbg.generated
     */
    List<SysLog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysLog record);
}